### ISSUE TITLE
module  'sepm' in File "calc_metrics.py"

### ISSUE THREAD

**Issue by MichaelChen147** [zelokuo/VPIDM#3]
![image](https://github.com/zelokuo/VPIDM/assets/33444924/dc06567b-5c98-49c1-aaf5-ed280e23b307)
Thank you so much for sharing your great work!
I met a error when running the file "calc_metrics.py".
Did the project miss the file "sepm.py"?

**Comment by zelokuo** [comment]
Thanks, Michael. The missing file is uploaded, please try it again.
